### PR TITLE
ESP32 example with deep sleep and fast re-joining after wake-up

### PR DESCRIPTION
**Pull request by matthias-bs**
Example sketch showing how to periodically poll a sensor and send the data to The Things Network.

Based on simple_sensor_bme280.ino with the following modifications: 
- reading the sensor data is replaced by a stub
- implements power saving by using the ESP32 deep sleep mode
- implements fast re-joining after sleep by storing network session data in the ESP32 RTC RAM
- LoRa_Serialization library is used for encoding of various data types into bytes

### CODE REVIEW

**Comment by matthias-bs** [comment]
Added fix for compiler warning with Arduino core v2.0.x

Warning:
```
/home/runner/Arduino/libraries/MCCI_Arduino_LoRaWAN_Library/src/Arduino_LoRaWAN.h:965:87: warning: missing initializer for member 'Arduino_LoRaWAN::SessionStateHeader::Size' [-Wmissing-field-initializers]
         SessionState m_savedSessionState { .Header = { .Tag = kSessionStateTag_Null } };
```

Fix:
```
SessionState m_savedSessionState { .Header = { .Tag = kSessionStateTag_Null, .Size = 0 } };
```

**Comment by terrillmoore** [comment]
Thanks, sorry for the delay in review.

**Comment by terrillmoore** [comment]
Pull request adopted and merged to master after rebase. Thanks!

**Comment by matthias-bs** [comment]
Thanks!

**Pull request closed without merging**
